# Generated by Django 3.2.4 on 2021-07-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='article-name', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(null=True, upload_to='blog-images')),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
