# Generated by Django 3.1.3 on 2021-06-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello world', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
