# Generated by Django 3.2.4 on 2021-06-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0003_auto_20210627_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello world', max_length=50)),
                ('question', models.CharField(default='questionjnjifd', max_length=150)),
                ('answer', models.CharField(default='A', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
    ]
