# Generated by Django 3.2.4 on 2021-06-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0004_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='hello world', max_length=50)),
                ('selected_answer', models.CharField(default='A', max_length=10)),
                ('answered_correctly', models.BooleanField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcqgenerator.question')),
            ],
        ),
    ]
