# Generated by Django 3.2.4 on 2021-06-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0005_auto_20210628_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
