# Generated by Django 3.2.4 on 2021-06-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0006_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_choices',
            field=models.CharField(choices=[('A', 'Freshman'), ('B', 'Sophomore'), ('C', 'Junior'), ('D', 'Senior'), ('E', 'Graduate'), ('F', 'Graduate'), ('G', 'Graduate')], default='A', max_length=1),
        ),
    ]
