# Generated by Django 3.2.4 on 2021-06-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0007_question_answer_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='hello world', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('options', models.CharField(choices=[('A', 'Freshman'), ('B', 'Sophomore'), ('C', 'Junior'), ('D', 'Senior'), ('E', 'eeGraduate'), ('F', 'ffGraduate'), ('G', 'ggGraduate')], default='A', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_choices',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mcqgenerator.answer'),
        ),
    ]
