# Generated by Django 3.2.4 on 2021-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0009_auto_20210629_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='options',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='letter_key',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default='hello world', max_length=250),
        ),
    ]
