# Generated by Django 3.2.4 on 2021-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0011_answer_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_selected',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='letter_key',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
