# Generated by Django 3.2.4 on 2021-07-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0012_auto_20210629_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_selected',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='letter_key',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
