# Generated by Django 3.2.4 on 2021-07-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0013_auto_20210702_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture',
        ),
    ]
