# Generated by Django 3.2.4 on 2021-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcqgenerator', '0014_remove_lecture_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture',
            field=models.FileField(null=True, upload_to='lectures'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='text',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
